### ISSUE TITLE
Build failed on iOS with 'dart:js' error

### ISSUE THREAD

**Issue by chyiiiiiiiiiiii** [amplitude/Amplitude-Flutter#158]
## Expected Behavior

Should run the app successfully.

## Current Behavior

It appears the error about dart:js is not available.

## Steps to Reproduce
 

1. Use newest version amplitude_flutter: ^3.16.0
2. Run iOS

## Environment
- SDK Version: v3.16.0
- Flutter Version: v3.13.6
- Device: iPhone 15 Pro Simulator

![iShot_2023-11-01_16 47 26](https://github.com/amplitude/Amplitude-Flutter/assets/15103960/17bc05fd-e80f-4a84-88dc-9f858af2c7bf)

**Comment by Mercy811** [comment]
Hi @chyiiiiiiiiiiii, thanks for choosing Amplitude. 

The error message you're encountering suggests that the Dart library 'dart:js' is being used in your Flutter project, but it's not available on the iOS platform. This is because 'dart:js' is a library intended for web development and is not supported in Flutter applications that target iOS or Android. To resolve this issue, you'll need to identify where 'dart:js' is being used in your project. 

I confirm that Amplitude Flutter SDK is not using 'dart:js" and I can run the [example project](https://github.com/amplitude/Amplitude-Flutter/tree/main/example) on my local. 

I would suggest to check if it's using elsewhere in your project. Hope this helps. 



<img width="1154" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/31029607/4728407e-76cb-409c-b85d-51ad9a9a7712">

**Comment by jagged91** [comment]
FYI, I had the same issue until I realized that VSCode automatically imported the JS version of the library when I added the init function. Just in case others see the same issue.
