### ISSUE TITLE
Migration guider to 4 ver

### ISSUE THREAD

**Issue by andim27** [amplitude/Amplitude-Flutter#199]
1) Please check/correct all what your write in migration on real project
The migration guide does not show correct way to upgrade
Example: Base_event not included (check Initialisation section)

2) ios:
error:  CDN: trunk Repo update failed - 6 error(s):
CDN: trunk URL couldn't be downloaded: CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/f/4/d/Amplitude/8.19.3/Amplitude.podspec.json Response: Failure when receiving data

**Comment by Mercy811** [comment]
Hi @andim27, `BaseEvent` is covered in [logEvent() section](https://amplitude.com/docs/sdks/analytics/flutter/flutter-sdk-4-0-migration-guide#logevent). The Flutter 4.x should use Amplitude-Swift instead of Amplitude-iOS (which is used by old Flutter SDK <=v3.x). Please make sure you updated the dependency by following https://amplitude.com/docs/sdks/analytics/flutter/flutter-sdk-4-0-migration-guide#dependencies

**Comment by Mercy811** [comment]
Close this issue as no updates. Feel free to reopen it!
