### ISSUE TITLE
How to use Session Replay feature?

### ISSUE THREAD

**Issue by emanuel-braz** [amplitude/Amplitude-Flutter#206]
## Summary

I need to implement Session Replay feature in several screens on Flutter app

**Comment by izaaz** [comment]
@emanuel-braz we don't have support for flutter yet. This is in our backlog and we'll update this thread when we build support for this.

**Comment by TimurMukhortov** [comment]
Hello 
Thanks for your product!

Are there any updates for recording sessions replays for the flutter web version?

**Comment by epszteyn** [comment]
Hello. Is there any estimate fro when Session Replay will be available on Flutter?

**Comment by izaaz** [comment]
Unfortunately we don't have an ETA to share as of now.

**Comment by justatipfromthedeadsequoiatree** [comment]
Hi @izaaz @Mercy811 ,

First of all, sorry for the unexpected tag.

I’ve successfully integrated the Amplitude Session Replay iOS SDK into our Flutter app. However, I’m currently only able to capture gestures — the replay shows a grey screen instead of the actual UI.

How can I enable full UI capture for a Flutter app running on iOS?


**[Video recording showing a grey screen]**

https://github.com/user-attachments/assets/8b2cdcde-9f77-4aa7-8403-8ff6297a2355

Any help would be greatly appreciated. Thank you!

**Comment by Arbimig** [comment]
Hi @justatipfromthedeadsequoiatree

Were you able to resolve the issue with the grey screen and achieve full UI capture? If so, could you share how you added Session Replay support to your Flutter app?

Thanks for any insights you can provide!
