### ISSUE TITLE
How do I log idfa and google ad id?

### ISSUE THREAD

**Issue by shredding** [amplitude/Amplitude-Flutter#29]
How do I report idfa or google ad id through this SDK?

I already have both reliably setup (we're using adjust as well) and available as String - but I don't know how to pass them to amplitude.

**Comment by haoliu-amp** [comment]
Please follow this page to enable idfa or adid reporting, there're a few things you need to set up. https://developers.amplitude.com/docs/ios-ios-advertising-id-idfa

Also If you wanna idfa working on iOS, please use v2.2.2 below. Since v2.2.3, we make iOS idfa fetching to be fully customer driven by providing a callback, but we haven't expose that API inside Flutter SDK. We will work on this next.
