### ISSUE TITLE
Google Play Services SDK not found for app set id! 

### ISSUE THREAD

**Issue by eli1stark** [amplitude/Amplitude-Flutter#98]
## Summary
Is it considered an error for Amplitude? Can it function with this error, I haven't published my app yet.

**Comment by bohan-amplitude** [comment]
Hi @eli1stark ,

Can you provide more detail about the error? Thank you very much.

**Comment by eli1stark** [comment]
It just prints "Google Play Services SDK not found for app set id!" at the debug console after init. No exceptions, just the print statement. I don't know what else to say) So, the question is, should I ignore it? Is this okay? Will it affect any functionality of Amplitude?

**Comment by yuhao900914** [comment]
Hi @eli1stark,
In Android native, we provide the method that [uses app set id as a device Id](https://github.com/amplitude/Amplitude-Flutter/blob/main/lib/amplitude.dart#L293).
If you do enable that, the error means the device Id value will be an unexpected value. Since we cannot get the app set id, the logic will still auto-generated a device id for you. If that is the case, please check here to see the [instruction](https://developers.amplitude.com/docs/android#advertising-id) about how to get the app set id.  
But if you didn't enable use app set id as a device id, you are all good.

**Comment by eli1stark** [comment]
Thanks
